### ISSUE TITLE
Errors on ./installvagrant.sh 

### ISSUE THREAD

**Issue by sirkitree** [levidehaan/drupaldeploy#2]
While running `./installvagrant.sh` I get the following:

``` bash
expr: syntax error
expr: syntax error
expr: syntax error
```

edit: osx 10.10.1

**Comment by levidehaan** [comment]
is that all the output from the command?

**Comment by sirkitree** [comment]
Unfortunately yes :( Is there anything I can check to see if I'm missing
something that should be installed?

**Comment by levidehaan** [comment]
Well what it does is first
Install homebrew if it's not installed
it installs a lib called dialog using this command:

```
brew install dialog
```

it installs wget using the above command.

it then installs vagrant if it's not installed using this command:

```
wget https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2.dmg
hdiutil mount vagrant_1.6.3.dmg
```

**Comment by sirkitree** [comment]
Yup, could probably just put this in the install instructions as steps
rather than providing a script that may or may not work other systems not
tested.

**Comment by levidehaan** [comment]
Roger that will do :) thanks!

**Comment by levidehaan** [comment]
Added this information to the readme.
